### ISSUE TITLE
Allow multiple tap dances in a row

### ISSUE THREAD

**Issue by adkron** [keyboardio/Kaleidoscope-TapDance#12]
Currently when tap dancing on a key if you hit the key more than there are slots the last slot is chosen and the extra taps are thrown away. I propose that when the max is reached the max key event is sent and the tap dance is terminated so that a new tap dance can begin.

An example and reasoning can be found at https://community.keyboard.io/t/tapdance-and-space-period-switching/621/34

**Comment by algernon** [comment]
This should be reasonably easy to implement... we'll need something like `TapDance::release`, except for the `bitWrite` stuff and returning a key. We could call it `TapDance::reset`, make it public (so user code could opt to use it too), and call it from `tapDanceActionKeys` whenever we reached `max_count`.

I'll try to get around to do this soon. Harder part of it is testing and making sure things work.

**Comment by algernon** [comment]
Due to the plugin being merged into the [Kaleidoscope](https://github.com/keyboardio/Kaleidoscope) monorepo, issues are being migrated over there. This issue is going to be tracked further as keyboardio/Kaleidoscope#394.
