### ISSUE TITLE
Unexpected quick keypress behavior

### ISSUE THREAD

**Issue by mikepugh** [keyboardio/Kaleidoscope-TapDance#15]
I've noticed the TapDance plugin has some timing issues with respect to rapid key presses.

For example, I have remapped my model01 enter key to be a 3 tap dance sequence of: - _ | 

If I press "enter" followed by "space" I get this: - -

If I press "enter" "space" "enter" I get this: - -__

Note that it isn't particular to the space key, if I press "enter" "k" "enter" I get this: -k-

This behavior occurs when the keys are pressed pretty quickly together - for reference I type at ~100 WPM. If I slow down quite a bit it's fine. The problem seems to occur if I hit a tap dance key followed by some other key before tap dance has a chance to timeout. 

Also if I quickly press two different tap dance enabled keys, I also get unexpected behavior. For example, I have remapped my esc key to a 2 tap dance sequence of: ( { and my butterfly key to be ) }.

If I press "esc" "butterfly" I get (} when I would expect ()

Below is the section of my custom firmware that sets  this up for me. I tried to pull latest but I'm running into some compilation issues, I'll try that again sometime soon and update this issue if the latest version fixes the issue. I'll also see if I can try and debug this a bit, but I'm a bit rusty with C.

```
#define Chord_CtrlAltDel LCTRL(LALT(Key_Delete))

// TapDance Enums
enum {
  L_PC,    // Left Paren Curly 
  R_PC,    // Right Paren Curly 
  COLON,
  HUP,      // Hyphen Underscore Pipe
  BRACKETS,   // Single and Double Quotes
  EQPL,     // Equals Plus,
  NUM_LOGIN // NumLock and Ctrl+Alt+Del
};

// TapDance ctions

void tapDanceAction(uint8_t tap_dance_index, byte row, byte col, uint8_t tap_count, kaleidoscope::TapDance::ActionType tap_dance_action) {
  switch (tap_dance_index) {
    case L_PC:
      return tapDanceActionKeys(tap_count, tap_dance_action, Key_LeftParen, Key_LeftCurlyBracket);
    case R_PC:
      return tapDanceActionKeys(tap_count, tap_dance_action, Key_RightParen, Key_RightCurlyBracket);
    case COLON:
      return tapDanceActionKeys(tap_count, tap_dance_action, LSHIFT(Key_Semicolon), Key_Semicolon);
    case HUP:
      return tapDanceActionKeys(tap_count, tap_dance_action, Key_Minus, LSHIFT(Key_Minus), Key_Pipe);
    case BRACKETS:
      return tapDanceActionKeys(tap_count, tap_dance_action, Key_LeftBracket, Key_RightBracket);
    case EQPL:
      return tapDanceActionKeys(tap_count, tap_dance_action, Key_KeypadAdd, Key_Equals);
    case NUM_LOGIN:
      return tapDanceActionKeys(tap_count, tap_dance_action, LockLayer(NUMPAD), Chord_CtrlAltDel);
  } 
}

// *INDENT-OFF*

const Key keymaps[][ROWS][COLS] PROGMEM = {
  [QWERTY] = KEYMAP_STACKED
  (Key_Escape,   Key_1, Key_2, Key_3, Key_4, Key_5, Key_LEDEffectNext,
   Key_Backtick, Key_Q, Key_W, Key_E, Key_R, Key_T, Key_Tab,
   Key_PageUp,   Key_A, Key_S, Key_D, Key_F, Key_G,
   Key_PageDown, Key_Z, Key_X, Key_C, Key_V, Key_B, TD(L_PC),
   Key_LeftControl, Key_Backspace, Key_LeftGui, Key_LeftShift,
   OSL(FUNCTION),

   TD(BRACKETS),  Key_6, Key_7, Key_8,     Key_9,         Key_0,         TD(NUM_LOGIN),
   TD(HUP),     Key_Y, Key_U, Key_I,     Key_O,         Key_P,         Key_Equals,
                  Key_H, Key_J, Key_K,     Key_L,         Key_Semicolon, Key_Quote,
   TD(R_PC),  Key_N, Key_M, Key_Comma, Key_Period,    Key_Slash,     Key_Minus,
   Key_RightShift, Key_Enter, Key_Spacebar, Key_LeftAlt,
   LockLayer(FUNCTION)),
```

**Comment by algernon** [comment]
Thanks for reporting this! I'm seeing the same problem too, but for one reason or another, always forgot to open an issue to remind myself to look into it.

I *suspect* that the reason this happens is that TapDance waits for the key to be fully released, and fires an event once that happens, even if it was interrupted first. It would need to track if a key was interrupted, and not fire a release event if it was, but just ignore it (or mask the key).

I'll try to get around to fix it in the next few days.

**Comment by algernon** [comment]
Hmm. Adding a bit of debugging code, it seems we have deeper issues. Rolling my fingers over a tap-dance key, then two others, I get an "interrupt, hold, hold, interrupt, release" sequence. The hold is okay, but the second interrupt is wrong, so is the release.

**Comment by algernon** [comment]
Hm. The 'release' is correct, but the second interrupt is not.

**Comment by algernon** [comment]
New idea: instead of a set of state bitmaps, we should have a single array with the current state of each tap-dance key. We could build a state machine on top of it, and make sure we only transition between states that make sense, and ignore the rest. I think that'd help most... it would also simplify the code considerably, at the cost of some minor increase in RAM usage. Or perhaps not even that.

**Comment by taylon** [comment]
It is making the plugin unusable to me, crashing my text editor constantly because of the quick keypress behavior :(

Any updates on a fix?

**Comment by algernon** [comment]
Quick update: I'm working on this right now. Well, on redoing TapDance using a state machine I outlined above, which should fix this issue as well.

**Comment by algernon** [comment]
Due to the plugin being merged into the [Kaleidoscope](https://github.com/keyboardio/Kaleidoscope) monorepo, issues are being migrated over there. This issue is going to be tracked further as keyboardio/Kaleidoscope#393.
